### ISSUE TITLE
[Proposal] New Public Reverse Proxy middleware

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-aspnetcore#11]
## Abstract
New middleware will be used to expose services from inside of the Service Fabric cluster publicly without the need to use any other 3rd party services (except of the load balancer). Service using such a middleware will scale together with the cluster,

### Features for V1
* Rule-based engine integrated with the Service Fabric configuration service
  * Graceful rules reload without service restarting
  * Rules for mapping urls to Service Fabric Reverse Proxy Urls i.e. /{PartitionId}/
  * Multiple port/ip-address support to allow IP-based SSL on L4 load balancer
* Support for removing all the unsecure (Reverse Proxy-related) headers and query string parameters from the URL
* Kernel caching support on Windows (HTTP.SYS)
* Web Sockets support
* **Requires** Service Fabric Reverse Proxy
* Request logging support

### Future features
* xplat caching support
* compression support
* SNI-support
* direct-service connectivity, resolution and retry (removing dependency on the Service Fabric Reverse Proxy)
* request rate throttling engine
* some WAF-like rules
* Any further ideas invented by the community

## Implementation
* I would be happy to create a PR for V1 (I have a working prototype).
* It should be a separate project as it will introduce new dependencies and it is intended to be used in very specific services.
* I would like to use https://github.com/aspnet/Proxy including my approved-but-not-merged-yet patches aspnet/Proxy#46

**Comment by grahamehorner** [comment]
could this not be achieved by a ServiceFabric management component that allows communication with network load balancer so as when Services instances on nodes change or nodes get added/removed the load balancer is informed/updated ?

**Comment by mkosieradzki** [comment]
@grahamehorner 

If by NLB you mean L4 load balancer then no:
- You cannot access stateful services
- Service resiliency will be bad (you loose retries on failover)
- No support for proper port sharing

If by NLB you mean L7 load balancer -> then you don't need any management component. Service Fabric Reverse Proxy is more than enough. you only need a strong enough rules system on your L7 Load Balancer. This specific middleware is intended to replace L7 load balancer.

**Comment by vturecek** [comment]
@mkosieradzki If anything I would split this out into a separate project, but as far as gateways are concerned we now integrate with API Management (more info on that is on the way), which does service routing and has a very rich set of routing rules built in, so for now I don't think we'd want to take up building our own.

**Comment by mkosieradzki** [comment]
@vturecek API Management is a great service, unfortunately there is no such thing on-premises.

But I totally understand.

In that case I will keep using my current solution, and maybe in future we can consider coming back to this topic of more people are interested. It is also very plausible that some existing solutions will be utilized for this purpose like nginx or haproxy.
