### ISSUE TITLE
WebListener renamed to HttpSysServer in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by vturecek** [Azure/service-fabric-aspnetcore#15]
We'll need to consider renaming our listener/package at some point as well.

aspnet/HttpSysServer#358

**Comment by johnbindel** [comment]
Hey Vaclav, I just put together a pull request for this- https://github.com/Azure/service-fabric-aspnetcore/pull/16
Feel free to hold off on merging until it's an appropriate time.
Cheers, John

**Comment by vturecek** [comment]
@johnbindel Right on, thanks John! We'll keep that on the backburner until it's time.

**Comment by juho-hanhimaki** [comment]
Is there any schedule for this now that 2.0 is out?

Looking forward to migrating to 2.0.

**Comment by johnbindel** [comment]
Aman commented that they will be releasing an HttpSysListener nuget package for aspnetcore 2.0. @amanbha, what does the timeline look like for this?
https://github.com/Azure/service-fabric-aspnetcore/pull/16#issuecomment-322085630

**Comment by amanbha** [comment]
It will be part of our next release, ETA is mid to end of Sept.

**Comment by lapuyaloca** [comment]
I just created my first ASP.NET Core 2 Stateless Service Fabric Reliable service but the first thing I notice is that now, by default uses the KestrelCommunicationListener instead of the WebListenerCommunicationListener used in core 1.X. It seems it has been removed from the service fabric asp.net core libraries. What Am I missing?

**Comment by vpoorshab** [comment]
@lapuyaloca 
install the package for weblistener
Microsoft.ServiceFabric.AspNetCore.WebListener

**Comment by amanbha** [comment]
Microsoft.ServiceFabric.AspNetCore.HttpSys nuget is now available
