### ISSUE TITLE
Reverse proxy and Application Insights integration issues

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-aspnetcore#18]
Related to: Microsoft/ApplicationInsights-aspnetcore#463

IMO this middleware should be modified to accomodate two differences.

Again let's consider following scenario
We have a public site: https://mydomain.com/mypath
It is handled locally by http://localhost:1234/{generated unique id}/mypath

1. First of all there should be an option to strip the generated unique path to make it proxy friendly. Basically PathBase in code below should be empty if this option is set.

https://github.com/Azure/service-fabric-aspnetcore/blob/develop/src/Microsoft.ServiceFabric.AspNetCore/ServiceFabricMiddleware.cs#L89-L102

2. Second, I am not convinced about setting values back to original values after invoking nested middleware. As it breaks:
ctx.Response.OnStarting() and ctx.Response.OnCompleted()
in both events ctx.Request will present original Path and PathBase

For example Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware does not recover the original Scheme and Host values. It affects how Application Insights for ASP.NET Core is working.

After those two improvements, if HttpMethodOverrideMiddleware is used, it should not only report nicely https://mydomain.com/mypath making it easier to analyze AI logs, but also make it easier to use some authentication middlewares and MVC.

**Comment by mkosieradzki** [comment]
Regarding 1st point. It's a no-issue, as it can be handled just by setting PathBase = PathString.Empty in the next middleware. So the only change actually needed is to remove the original-values reverting behavior.

**Comment by mkosieradzki** [comment]
Current behavior (recovering original Path and PathBase) is consistent with MapPath middleware.

So I believe this issue (stripping automatically generated PathBase) should be handled in ApplicationInsights-ServiceFabric, but still I am not 100% sure.

**Comment by amanbha** [comment]
For 2nd point, you pointed correctly that its consistent with other middlewares and just sets "paths" to what it was for the previous middleware.  I believe it should be handled in ApplciationInsights-ServiceFabric middleware.

**Comment by mkosieradzki** [comment]
@amanbha
Thanks for your answer. I appreciate it. In that case I will pursue improvements to ApplicationInsights-ServiceFabric. I will close this issue when my proposal in ApplicationInsights-ServiceFabric is resolved.
