### ISSUE TITLE
[Proposal] Create a FabricReverseProxyIntegration middleware

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-aspnetcore#2]
I am basically using such a middleware as below on every service. This might make a useful addition to address [Special handling for port sharing services](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy#special-handling-for-port-sharing-services).
```
        public static IApplicationBuilder UseFabricReverseProxyIntegration(this IApplicationBuilder app) => app.Use(async (ctx, next) =>
        {
            await next();
            if (ctx.Response.StatusCode == 404)
                ctx.Response.Headers.Add("X-ServiceFabric", "ResourceNotFound");
        });
    }
```

If this proposal is accepted, I will be happy to create a proper pull request with a proper middleware, etc.

In future this middleware might also handle X-Forwarded headers, but this requires some cleanup on the Reverse Proxy side first: Azure/service-fabric-issues#113 (it might be handled just by the ASP.NET Core Basic proxy middleware). My intention would be to create a similar middleware to the IISIntegration.

**Comment by vturecek** [comment]
@amanbha FYI.
@mkosieradzki Thank you, yes I think this is a great idea and very necessary if you're using the reverse proxy. Happy to take this in if you can prepare a PR!

**Comment by Marusyk** [comment]
@mkosieradzki  Could you please suggest me how do you use that middleware with `app.UseMvc();`?  Becase in my case when I try to add header I can't because `context.HttpContext.Response.HasStarted = true`

**Comment by senj** [comment]
I think this doesn't work if I create an ObjectResult with statusCode 404 and return it?

**Comment by mgrishkov** [comment]
For me it works. I return NotFound result.
Unfortunatly it works only for 404

**Comment by mkosieradzki** [comment]
Yes, there might be a problem if ctx.Response.HasStarted is true.

We need to decide here what to do in this case. Do not add header (it's too late) and:
1. Check if proper header had been already added by the developer. If not log warning.
2. Do nothing.

**Comment by Marusyk** [comment]
We solved that problem with following code
```

public async Task Invoke(HttpContext context)
{
	context.Response.OnStarting(state =>
	{
		var httpContext = (HttpContext)state;
		if (httpContext.Response.StatusCode == (int)HttpStatusCode.NotFound)
		{
			httpContext.Response.Headers.Add("X-ApiGateway-ResourceNotFound", string.Empty);
		}
		return Task.CompletedTask;
	}, context);

	await _next.Invoke(context);
}
```

**Comment by mkosieradzki** [comment]
@Marusyk Nice. We should definitely use your approach.

**Comment by senj** [comment]
Why do you use "X-ApiGateway-ResourceNotFound"?

**Comment by Marusyk** [comment]
@senj Our ApiGateway makes decision to retry when 404 or return 404 if resource not found. The  "X-ServiceFabric" header is quite common and doesn't tell what data I'm going to use. So we decided to use unique header like "X-ApiGateway-ResourceNotFound" which does not require checking the value. This header exists only when requested resource not found

**Comment by vturecek** [comment]
@Marusyk The X-ServiceFabric header will have "ResourceNotFound" as the value and you'll need that if you're using the Service Fabric reverse proxy.
