### ISSUE TITLE
Please make Microsoft.ServiceFabric.AspNetCore a separate package

### ISSUE THREAD

**Issue by mkosieradzki** [Azure/service-fabric-aspnetcore#20]
I could use it for example here: Microsoft/ApplicationInsights-ServiceFabric#13

**Comment by amanbha** [comment]
@mkosieradzki Could you help me understand how making it a separate nuget package helps, the dll is available in Microsoft.ServiceFarbic.AspNetCore.Kestrel and Microsoft.ServiceFarbic.AspNetCore.WebListener?

**Comment by mkosieradzki** [comment]
@amanbha
When creating a dependent middleware I can take listener as a parameter exactly the same way as currently existing middlewares.

I cannot reference neither weblistener nor kestrel version, because I want to make this new middleware server independent.

Alternatively we can take just url as an argument and avoid creating dependency additional dependency, however I thought it would be more natural to make the AI-integration API similiar to the service fabric middleware.

**Comment by amanbha** [comment]
agree on keeping it server independent, trying to understand the scenario, if its a separate nuget package. what functionality from it do you want to use or extend in your other middleware, can it achieve that just by being the next middleware?

**Comment by mkosieradzki** [comment]
Exactly, I only need the type AspNetCoreCommunicationListener and access its UrlSuffix field (but also service context). This is why I am a bit confused here.
It's like a choice between the following: (the name `UseMyTelemetry` is only temporal)
```
UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.UseUniqueServiceUrl).UseMyTelemetry(sctx, listener.UrlSuffix)
```
or 
```
UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.UseUniqueServiceUrl).UseMyTelemetry(listener)
```

Maybe this `AspNetCoreCommunicationListener` should be in some `Microsoft.ServiceFabric.AspNetCore.Abstractions`?

**Comment by mkosieradzki** [comment]
Moreover maybe it would be a good idea if UseServiceFabricIntegration would register AspNetCoreCommunicationListener as a service in DI container? In that case entire service fabric telemetry integration could happen parameterless?

**Comment by amanbha** [comment]
@mkosieradzki I will create a new package Microsoft.ServiceFabric.AspNetCore.Abstractions for this, it will be starting with our next release (5.7)

**Comment by mkosieradzki** [comment]
Thanks @amanbha. I appreciate it.
