### ISSUE TITLE
ASP.NET Core 2.0

### ISSUE THREAD

**Issue by grahamehorner** [Azure/service-fabric-aspnetcore#21]
I'm getting the following error in ServiceFabric when using ASP.NET Core 2.0 

Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures in_Node_2 API call: IStatelessServiceInstance.Open(); Error = System.MissingMethodException (-2146233069)
**Method not found: 'Void Microsoft.AspNetCore.Hosting.IWebHost.Start()'.**
   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__14.MoveNext()

**Comment by grahamehorner** [comment]
the issues looks to be the following 

 public virtual Task<string> OpenAsync(CancellationToken cancellationToken)
....
            this.webHost.Start();
the interface of IWebHost has been broken!? :'( the Start has been removed and replace with StartAsync

https://github.com/aspnet/Hosting/issues/1124

**Comment by vturecek** [comment]
@grahamehorner Yup we're tracking these changes in #6 and planning to roll up asp.net 2.0 support with our .NET Standard 2.0 support later this fall.

**Comment by grahamehorner** [comment]
@vturecek @davidfowler & team have re implemented the Start method so not to break other code, and ServiceFabric is now working with preview 3 builds of asp.net core, however the uri displayed in the explorer ui is an IPv6 http::[::] which is a different behaviour and I have logged this as an issue

**Comment by vturecek** [comment]
@grahamehorner Thanks for finding that, we're looking at getting a fix out for this soon.
