### ISSUE TITLE
dotnet run support?

### ISSUE THREAD

**Issue by kimbell** [Azure/service-fabric-aspnetcore#22]
Currently the documentation states 

> While ASP.NET Core apps can run on .NET Core or on the full .NET Framework, Service Fabric services currently can only run on the full .NET Framework. This means when you build an ASP.NET Core Service Fabric service, you must still target the full .NET Framework.

Some time ago, the ASP.NET Core team tried to change things so that 2.0 would only run on .NET Core and not .NET Framework. This was later reverted due to community feedback. https://github.com/aspnet/home/issues/2022

Since they already tried once, it's just a matter of time before it becomes reality. Currently Service Fabric doesn't support starting applications using 'dotnet run'. Any plans on adding this support?

**Comment by amanbha** [comment]
We would make our binaries compatible with for netstandard2.0, at that point running net core apps would be possible.

**Comment by amanbha** [comment]
We are working on building our Programming model binaries net standard 2.0 at which point it would be possible to run netcore apps.

**Comment by kimbell** [comment]
So, will the XML configuration allow you to just specify a dll rather than en exe?

**Comment by vturecek** [comment]
@kimbell That you can already do today with a [Guest EXE](https://docs.microsoft.com/azure/service-fabric/service-fabric-deploy-existing-app) service, you just have to use a .cmd file to execute dotnet MyApp.dll. For example, your ServiceManifest.xml would have:

```
    <EntryPoint>
      <ExeHost>
        <Program>run.cmd</Program>
        <Arguments></Arguments>
        <WorkingFolder>CodePackage</WorkingFolder>
        <!-- Uncomment to log console output (both stdout and stderr) to one of the
             service's working directories. -->
        <!-- <ConsoleRedirection FileRetentionCount="5" FileMaxSizeInKb="2048"/> -->
      </ExeHost>
    </EntryPoint>
```

Your code package would contain your application DLLs and `run.cmd` which would simply call:

`dotnet MyApp.dll`

As @amanbha mentioned, all of our .NET assemblies will target .NET Standard 2.0 later this fall, so if you're using one of our NuGet packages, you'll be able to compile against .NET Core 2.0.

**Comment by kimbell** [comment]
Wrapping it in a run.cmd is so simple it just didn't occur to me. D'oh!

**Comment by petkit** [comment]
Does this mean that some kind of .NET Core package has to be pre-installed on each cluster node? I mean in order for the dotnet.exe to be available. What would be the simplest/recommended way to achieve this?

**Comment by adailsonfilho** [comment]
@petkit, I had the same question with me some time ago. I just found a sample project implementing a Reliable Service in .NET CORE for Service Fabric: https://github.com/Azure-Samples/service-fabric-dotnet-core-getting-started ...

**Comment by petkit** [comment]
Thanks @adailsonfilho, we managed to solve this however, by adding a custom script extension within the ARM-template (in the VM profile part of the SF scale set resource definition) configured to run the dotnet-install ps-script.
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/extensions-customscript

**Comment by vturecek** [comment]
@petkit +1, a VM extension is the best way to go. The other option is to build a self-contained deployment, which bundles the .NET Core runtime along with your application so that it's completely self-contained. The downside there is that you have to target a specific platform, so the application package is no longer portable across platforms, and of course the package will be larger. More info on that here: https://docs.microsoft.com/dotnet/core/deploying/

**Comment by PepijnGramberg** [comment]
@amanbha @vturecek  With the current preview (6.1.219-preview, 3.0.219-preview) netstandard libraries are available yet it looks like we still require the cmd "trick". We would like to get rid of this work around and make it code cleaner. Are there plans to support the netcoreapp dll directly as an entrypoint? And when can we expect this?
