### ISSUE TITLE
Service Fabric 5.7 MissingMethodException for ServiceInstanceListener

### ISSUE THREAD

**Issue by Eyedicious** [Azure/service-fabric-aspnetcore#24]
I am getting the following error when deploying after upgrading to Service Fabric 5.7  from Service Fabric 5.6.210 (On 5.6.210 this seemed to be working A-okay)

> Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false. Replica had multiple failures in_Node_0 API call: IStatelessServiceInstance.Open(); Error = System.MissingMethodException (-2146233069) Method not found: 'System.String System.Fabric.ServiceContext.get_PublishAddress()'.    at Microsoft.ServiceFabric.Services.Communication.AspNetCore.AspNetCoreCommunicationListener.OpenAsync(CancellationToken cancellationToken)    at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__20.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.d__14.MoveNext()

I am running my Service Fabric in a local cluster. I am using both KestrelCommunicationListener and WebCommunicationListener each in an individual service. Both Services report the same error. 
I create my listeners as follow: 

```
return new ServiceInstanceListener(serviceContext =>
            {
                return new WebListenerCommunicationListener(serviceContext, endpointName, (url, listener) =>
                {
                    loggingCallback(serviceContext, $"Starting WebListener on {url}");

                    return new WebHostBuilder().UseWebListener()
                                .ConfigureServices(
                                    services => services
                                        .AddSingleton(serviceContext))
                                .UseContentRoot(Directory.GetCurrentDirectory())
                                .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                                .UseStartup(startupType)
                                .UseUrls(url)
                                .Build();
                });
            }, String.IsNullOrEmpty(name) ? endpointName : name);
```

**Comment by amanbha** [comment]
What is the version for Service Fabic runtime installed on the machine, looks like the runtime installed is still 5.6.

**Comment by Eyedicious** [comment]
I feel like an outright fool. Indeed my ServiceRuntime was still 5.6, updating it to 5.7 resolved the issue flawlessly. A silly oversight of me, cheers for the quick response and the help!
