### ISSUE TITLE
Unable to create cluster SF 5.7.198.9494 on standalone server

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-aspnetcore#25]
I run following script to create a DEV cluster
`.\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath C:\Configs\ClusterConfig.json  -AcceptEULA` 
and I get exception:
`Runtime package cannot be downloaded. Check you internet connectivity. If the cluster is not connected to the internet,` but server has access to the internet and I can download CAB-file via browser.

OK, I downloaded CAB-file and to call next command:
`.\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath C:\Configs\ClusterConfig.json -FabricRuntimePackagePath C:\Install\MicrosoftAzureServiceFabric.5.7.198.9494.cab -AcceptEULA`

and get excpetion: 
`Create Cluster failed with exception: System.Management.Automation.CommandNotFoundException: The 'New-ServiceFabricCluster' command was found in the module 'ServiceFabric', but the module cou ld not be loaded. For more information, run 'Import-Module ServiceFabric'. ---> System.Management.Automation.CmdletInvocationException: Could not load type 'System.Fabric.Description.ServiceP ackageActivationMode' from assembly 'System.Fabric, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. ---> System.TypeLoadException: Could not load type 'System.Fabric.Descr iption.ServicePackageActivationMode' from assembly 'System.Fabric, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad,
Dictionary`2& cmdlets, Dictionary`2& providers, String& helpFile)
  ....` etc.

**How should I solve the error and create cluster?**

**Comment by mgrishkov** [comment]
Creation has been completed for 5.5.216.0 via following script:
`.\CreateServiceFabricCluster.ps1 -ClusterConfigFilePath C:\Configs\ClusterConfig.json -FabricRuntimePackagePath C:\Install\MicrosoftAzureServiceFabric.5.5.216.0.cab -AcceptEULA`

**But i still unable to install 5.5.220 and 5.7.198**

**Comment by mgrishkov** [comment]
It seems that I solve the issue by **removing** cluster, **clearing** and new **installation**.

**Comment by vturecek** [comment]
Just for future reference, this repo is specifically for ASP.NET Core integration with Service Fabric. For general questions like cluster setup, you'll have better luck at our main issues repo at https://github.com/Azure/service-fabric-issues/
