### ISSUE TITLE
Problem with aspnetcore.Kestrel

### ISSUE THREAD

**Issue by hugoterelle** [Azure/service-fabric-aspnetcore#26]
Using the latest Visual Studio 2017 15.3, I try to create a Service Fabric Application with Dotnet Core Web (Angular JS and dotnet core 2.0)

Everything works fine and can be deployed locally.

But I tried to upgrade the nuget packages.  And the system is not working anymore.  After upgrading packages one by one, I discovered that Microsoft.ServiceFabric.AspNetCore.Kestrel is the problem (from 2.6.220 to 2.7.198).

Is there a particular reason?

**Comment by amanbha** [comment]
Whats the error you are getting? What is the runtime version installed on the machine? It has to be 5.7.198.

**Comment by hugoterelle** [comment]
Thank you, it solved the problem after upgrading Service Fabric runtime to version 5.7.198
