### ISSUE TITLE
HRESULT for OPTION/GET request

### ISSUE THREAD

**Issue by mgrishkov** [Azure/service-fabric-aspnetcore#29]
I faced a problem with OPTION/GET requerst to a stateless AspNet.Core WebApi service. In some cases (I cannot identify when) client get 500 error with header **X-Error-HRESULT:80090321** or **X-Error-HRESULT: 80072F8F**. I cannot find any information for that HRESULT applied to a SF. 

```
Request URL:https://?????
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:???.???.???.????:443
Referrer Policy:no-referrer-when-downgrade

Response Headers
Content-Length:0
Date:Tue, 05 Sep 2017 15:01:35 GMT
Server:Microsoft-HTTPAPI/2.0
X-Error-HRESULT:80090321
```
P.S. According to the NDA I have to hide some information with ?-symbol

**Comment by amanbha** [comment]
@mgrishkov This looks more like an ASPnetcore issue than a Service Fabric issue, could you please open it in aspnetcore repo.

**Comment by mgrishkov** [comment]
Thank you for your reply. I tried to upgrade NetCore SDK to the latest version. Let's see how it affects the issue.

**Comment by amanbha** [comment]
@mgrishkov Any updates on the issue, does it still repros for you, did you get a chance to ask this in aspnetcore repo.

**Comment by mgrishkov** [comment]
Upgrade to the latest aspnetcore didn't solve the issue. The only thing thst I got: it is almost impossible tp get the errors atnight time. It seems to me that it load depended.
I need more time to enroll another environment and test it to reproduce errors.

**Comment by mgrishkov** [comment]
It seems that upgrading SF up to 6.0 and switching dev-cluster to single node configuration have resolved the issue.
Are there any ideas what was the case of the issue?

**Comment by mgrishkov** [comment]
Unfortunately, but I catch the error again. But earlier an event log shows it, but now it doesn't. It makes investigation much difficulty... I'll create issue for aspnet core repo.

**Comment by mgrishkov** [comment]
Is it possible to log every request that comes through the reverse proxy?

**Comment by amanbha** [comment]
@mgrishkov  https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverse-proxy-diagnostics , Are you accessing the service via ReverseProxy, If yes, do you get the same error without ReverseProxy

**Comment by mgrishkov** [comment]
@amanbha I cannot understand how to log events. The dev-cluster hosted on the server hasn't got installed VS. Is it possible to log events into file or collect it remotely?

**Comment by amanbha** [comment]
@mgrishkov  is it in azure?

**Comment by mgrishkov** [comment]
No, it is standalone single node dev-cluster.

**Comment by amanbha** [comment]
On the one box, any events collector should be able to collect events, you can use PerfView

**Comment by mgrishkov** [comment]
Unfortunately, It seems that issue connected with environment. The issue may be closed.
