### ISSUE TITLE
Use PathSuffix from ServiceEndpoint

### ISSUE THREAD

**Issue by kostrse** [Azure/service-fabric-aspnetcore#3]
`Endpoint` in *ServiceManifest.xml* supports a `PathSuffix` attribute:

```xml
<Endpoints>
  <Endpoint Name="FooEndpoint" Type="Input" Protocol="https" Port="443" PathSuffix="/foo" />
</Endpoints>
```

This value publicly exposed via `ServiceEndpoint`.
Would be convenient if `WebListenerCommunicationListener` would use this value for construction of the URL [here](https://github.com/Azure/service-fabric-aspnetcore/blob/master/src/Microsoft.ServiceFabric.AspNetCore.WebListener/WebListenerCommunicationListener.cs#L44-L45).

Here is a sample from documentation:

```csharp
 new WebListenerCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
 {
     url += "/MyUniqueServicePath";

     return new WebHostBuilder()
         .UseWebListener()
         ...
         .UseUrls(url)
         .Build();
 })
```

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore

If the *url* would be used from `ServiceManifest`, the sample code would be reduced to:

```csharp
 new WebListenerCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
 {
     return new WebHostBuilder()
         .UseWebListener()
         ...
         .UseUrls(url)
         .Build();
 })
```

**Comment by vturecek** [comment]
@kostrse We considered this at one point but decided against it. Endpoint definitions are scoped to a service type, but you usually want a URL path suffix to be unique per instance of a service type to differentiate each instance from the others. 

For example, suppose you have MyWebServiceType with the following endpoint definition in ServiceManifest.xml:

`<Endpoints>
  <Endpoint Name="FooEndpoint" Type="Input" Protocol="http" Port="80" />
</Endpoints>
`
Then you create multiple instances of MyWebServiceType:

- fabric:/MyApp/MyWebService1
- fabric:/MyApp/MyWebService2

They both share the same endpoint definition. In order for them to run simultaneously on the same port (assuming you're using WebListener), they'll need unique URL prefixes. 

So yeah you can have PathSuffix automatically populate the URL in WebListenerCommunicationListener, but it'll only work if you only create a single instance of that service type, and that can set you up for failure. 

Ultimately, we'd like to split out that Endpoint definition in ServiceManifest.xml for different use cases.

**Comment by guibirow** [comment]
In you scenario would be easier to define these configurations using the config overrides and application parameters, isn't?
Today we have the same scenario and we use a powershell step to change ports because we couldn't do that as part of configuration override.

Why we can't have a service override as well?

**Comment by kostrse** [comment]
Agree that generation of URL based only on ServiceEndpoint alone is not suitable when one service type has several instances and each of them needs to be bound to a unique URL.

This is true whether `PathSuffix` value used or not.

The URL is not being supplied to WebListener directly, it is provided as a parameter to callback function, where you still can (if you wish) apply final modifications to the URL according to your naming strategy:

```csharp
new WebListenerCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
{
    // This optionally can be modified if really needed
    url += "/unique-instance-1145";

    return new WebHostBuilder()
        .UseWebListener()
        ...
        .UseUrls(url)
        .Build();
})
```

In case of multiple service instances, at could be combined with `PathSuffix` to result in URL like: `/FooEndpoint/unique-instance-1145`

Again, this is up to the user:
* It's not required to specify PathSuffix in ServiceEndpoint at all.
* The URL parameter value can be mutated in any way, or even discarded and WebListener can be provided with a completely different URL.

**Comment by vturecek** [comment]
@guibirow Yes we'd like to eventually get parameter overrides to flow into Endpoint definitions in ServiceManifest.xml. For now you have to have multiple service packages for each configuration you want or use some tokenizer/string replacement deal at build time (VSTS has a task for that).

@kostrse Programmatically creating the URL when you need to is the right idea. The PathSuffix property is mainly for guest EXE/containers that need to register a URL with the Naming Service. Again that's something I'd like to split out eventually; it's confusing the way it is today. We're worried that appending PathSuffix automatically will lead people down the wrong path and end up having to programmatically append a unique suffix anyway.

**Comment by ovebastiansen** [comment]
Does there exist a complete sample on how to get portsharing to work with https and certificates and weblisteners? I have found some hints about using a setupentrypoint and netsh commands. And have used overrideenvironmentvariables tags to get different certificates into local vs cloud, but it does not completely work. I have two servicefabric applications, that I would like to host the frontend part with weblistener, portsharing and a pathsuffix to separate the different applications. (I develop both parts so can enter different pathsuffix for both frontends) And frontends in this cases are a stateless aspnetcore webapi, that calls different statefull backends to do storage and computing.

**Comment by amanbha** [comment]
@ovebastiansen Since WebListener, to enable https for the endpoint, please take a look at https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources#example-specifying-an-https-endpoint-for-your-service

**Comment by levimatheri** [comment]
Why does this not work when I use `KestrelCommunicationListener`? It keeps saying I have to use `UsePathBase`.
