### ISSUE TITLE
Latest stateful ASP.Net Core template does not seem to work. (Asp.Net Core 2)

### ISSUE THREAD

**Issue by Eneuman** [Azure/service-fabric-aspnetcore#36]
I'm running VS 15.4 , Service Fabric SDK 6.0.211.9494 and Toolings 2.

I'm creating a new SF Project, and selecting the "Stateful ASP.Net Core" template from the latest Tooling preview. After the project has been created I'm deploying it localy without changing anything.
It failes to start with the error message 

> Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false. Replica had multiple failures during open on _Node_0. -2147024894 For more information see: http://aka.ms/sfhealth

and in VS it says

> XXXX is not ready, 1 partitions remaining

and the event log gives me this:

> Replica 131528218053279697 on node 0xBF865279BA277DEB0x864A976FBF4C200E for FT {a9023c01-9911-4db6-8ec7-a01504e1db24} failed with error 2147942402

The same problem occurs if I try and upgrade one of my existing working statefull ASP.Net Core 1.0.1. 

Can I change something in the template to get it working?

**Comment by amanbha** [comment]
Whats the exception when you try to debug it? Also what is the version of following nuget packages:
Microsoft.ServiceFabric.AspNetCore.Kestrel (if using Kestrel) or Microsoft.ServiceFabric.AspNetCore.WebListener if using WebListener.
Microsoft.ServiceFabric.Services
Microsoft.ServiceFabric

**Comment by Eneuman** [comment]
VS wont start the debugging session :(
I have attached a project showing the problem.
I also tried to upgrade to SDK 6.0.219.9494 and the same problem occured.

(It's just the latest default template with out any modifications)

[TestApp.zip](https://github.com/Azure/service-fabric-aspnetcore/files/1397365/TestApp.zip)

**Comment by ravipal** [comment]
@Eneuman I tried the attached app. It fails to build asking to update the platform to x64. Then I am able to deploy the application and it works.

**Comment by Eneuman** [comment]
I just tried to downloaded and publish it and it still gives me the same error :(
Can you please verify that you are running 6.0.219.9494 in your cluster?

This is the output I get from VS when deploying:

> 1>------ Build started: Project: Web1, Configuration: Debug Any CPU ------
1>Web1 -> C:\Users\PerBornsjö\Downloads\TestApp\TestApp\Web1\bin\Debug\netcoreapp2.0\win7-x64\Web1.dll
2>------ Build started: Project: TestApp, Configuration: Debug x64 ------
3>------ Publish started: Project: TestApp, Configuration: Debug x64 ------
3>Started executing script 'GetApplicationExistence'.
-------- Package started: Project: TestApp, Configuration: Debug x64 ------
3>Finished executing script 'GetApplicationExistence'.
3>Time elapsed: 00:00:04.9329429
Web1 -> C:\Users\PerBornsjö\Downloads\TestApp\TestApp\Web1\bin\Debug\netcoreapp2.0\win7-x64\Web1.dll
Web1 -> C:\Users\PerBornsjö\Downloads\TestApp\TestApp\Web1\obj\Debug\netcoreapp2.0\win7-x64\PubTmp\Out\
TestApp -> C:\Users\PerBornsjö\Downloads\TestApp\TestApp\TestApp\pkg\Debug
-------- Package: Project: TestApp succeeded, Time elapsed: 00:00:23.6805906 --------
3>Started executing script 'Deploy-FabricApplication.ps1'.
3>powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command ". 'C:\Users\PerBornsjö\Downloads\TestApp\TestApp\TestApp\Scripts\Deploy-FabricApplication.ps1' -ApplicationPackagePath 'C:\Users\PerBornsjö\Downloads\TestApp\TestApp\TestApp\pkg\Debug' -PublishProfileFile 'C:\Users\PerBornsjö\Downloads\TestApp\TestApp\TestApp\PublishProfiles\Local.1Node.xml' -DeployOnly:$false -ApplicationParameter:@{} -UnregisterUnusedApplicationVersionsAfterUpgrade $false -OverrideUpgradeBehavior 'None' -OverwriteBehavior 'SameAppTypeAndVersion' -SkipPackageValidation:$false -ErrorAction Stop"
3>Copying application to image store...
3>Upload to Image Store succeeded
3>Registering application type...
3>Register application type succeeded
3>Removing application package from image store...
3>Remove application package succeeded
3>Creating application...
3>
3>
3>ApplicationName        : fabric:/TestApp
3>ApplicationTypeName    : TestAppType
3>ApplicationTypeVersion : 1.0.0
3>ApplicationParameters  : { "Web1_PartitionCount" = "1";
3>                         "Web1_MinReplicaSetSize" = "1";
3>                         "Web1_TargetReplicaSetSize" = "1" }
3>
3>Create application succeeded.
3>
3>
3>Finished executing script 'Deploy-FabricApplication.ps1'.
3>Time elapsed: 00:00:36.4122604
3>Started executing script 'Get-ServiceFabricApplicationStatus'.
3>powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command "[void](Connect-ServiceFabricCluster -TimeoutSec:10 -WarningAction:'SilentlyContinue'); Import-Module 'C:\Program Files\Microsoft SDKs\Service Fabric\Tools\PSModule\ServiceFabricSDK\ServiceFabricSDK.psm1'; Get-ServiceFabricApplicationStatus -ApplicationName 'fabric:/TestApp' -ErrorAction Stop"
3>The application has started.
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Service Status:
3>fabric:/TestApp/Web1 is not ready, 1 partitions remaining.
3>
3>Something is taking too long, the application is still not ready.
3>Finished executing script 'Get-ServiceFabricApplicationStatus'.
3>Time elapsed: 00:00:45.2362795
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========

![error](https://user-images.githubusercontent.com/12099277/31792507-94432a0c-b51c-11e7-958d-5e84636653cb.png)
![nugets](https://user-images.githubusercontent.com/12099277/31792582-c4b86f08-b51c-11e7-8630-b7064cda09ae.png)

**Comment by ravipal** [comment]
I have the same version of SDK and runtime
![image](https://user-images.githubusercontent.com/1775825/31798243-72551912-b4e7-11e7-8ba1-3dce21174d00.png)

The same Test app that you attached works fine.
Will it ever come back to healthy state, say after a minute or so?. May be the machine is slow and takes a while to bring up the application. Other option is try to reset the cluster and see if that fixes the issue.

If you still run into the issue, then you may have to share the cluster trace.

**Comment by Eneuman** [comment]
No, it never goes up, and it's my local machine so it's fast.
Where can I find the cluster traces?

**Comment by amanbha** [comment]
If you cant do F5, could you try attaching to the service process. 
In the Program.cs where you are Registering the service, add following lines at the beginning of try block, (this will block until a debugger is attached), then publish the service and attach to the service process, once debugger attaches, it will go out of the while loop and you should be able to see the actualexception in debugger.

 while(!Debugger.IsAttached)
                {
                    Thread.Sleep(5000);
                }

**Comment by Eneuman** [comment]
I tried to add your code to my startup.cs, both before and and after the

```
ServiceRuntime.RegisterServiceAsync("Web1Type", context => new Web1(context)).GetAwaiter().GetResult();
ServiceEventSource.Current.ServiceTypeRegistered(Process.GetCurrentProcess().Id, typeof(Web1).Name);

```
code but the debugger wont give me any more information.
After I disabled "Just my code" debug, alots of the following errors are displayed in debug:

`Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll`

I have resinstalled the SDK, reset the local cluster and removed and reinstalled the service but the problem is still there.
.Net Core 1.0.1 Stateless Works
.Net Core 1.0.1 Statefull Works
.Net Core 2.0 Stateless Works
.Net Core 2.0 Statfull does not work 

Are there any other log files that can show me whats going on ?

**Comment by ravipal** [comment]
Is System.Private.CoreLib.dll in your package folder (TestApp\pkg\Debug\Web1Pkg\Code)?

**Comment by Eneuman** [comment]
Yes it is.
![image](https://user-images.githubusercontent.com/12099277/31839528-c92b72a4-b5e1-11e7-83b4-43839de51de7.png)

**Comment by Eneuman** [comment]
Looking at the error details it says:
Replica has been created on_Node_0.
Replica had multiple failures during open on _Node_0. -2147024894

**Comment by Eneuman** [comment]
Running the Web1.exe from command reveals this:

C:\Temp\TestApp\Web1\bin\Debug\netcoreapp2.0\win7-x64>Web1.exe

```
Unhandled Exception: System.Fabric.FabricConnectionDeniedException: Not authorized to connect ---> System.Fabric.Interop.Utility+COMWrapperException: Service Fabric Exception ---> System.Exception: Exception from HRESULT: 0x80071C43
   at System.Fabric.Interop.NativeRuntime.FabricEndGetNodeContext(IFabricAsyncOperationContext context)
   at System.Fabric.FabricRuntime.NativeFabricRuntimeFactory.GetNodeContextEndWrapper(IFabricAsyncOperationContext context)
   at System.Fabric.Interop.AsyncCallOutAdapter2`1.Finish(IFabricAsyncOperationContext context, Boolean expectedCompletedSynchronously)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.RuntimeContext.<GetOrCreateAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceFabric.Services.Runtime.ServiceRuntime.<RegisterServiceAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Web1.Program.Main() in C:\Temp\TestApp\Web1\Program.cs:line 34

C:\Temp\TestApp\Web1\bin\Debug\netcoreapp2.0\win7-x64>

```

**Comment by amanbha** [comment]
That's just saying there were some issues while opening the service replica.
You mentioned about "Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll"
Whats the exception detail, what file its complainting about?
Since it working both for @ravipal and me, Could you share your application package, we will compare it whats generated for our machines.

**Comment by Eneuman** [comment]
It doesn't say unfortently. Just a bunch of Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll..

You can find the complete build at:
https://links-my.sharepoint.com/personal/per_bornsjo_links_se/_layouts/15/guestaccess.aspx?docid=0e50002a6de964c2caa6e2712d86eb03c&authkey=AZo0bIdIIfNbuCRl3z_qGkw

**Comment by amanbha** [comment]
@Eneuman The binaries in the preview packages are not strong name signed so wondering if that is causing the issue. Would you be possible to have skype call and I can take a look at your machine. You can send me email at amanbha@microsoft.com to setup sometime for this.

**Comment by Eneuman** [comment]
Hi

I tried changing the localization to EN-US and published the project but the problem still exists.

Regards
Per

________________________________

**Comment by amanbha** [comment]
Its a stateful service issue being tracked in our issues repo at https://github.com/Azure/service-fabric-issues/issues/563

**Comment by amanbha** [comment]
Closing this one as its not specific to aspnet core, its related to stateful services and is being tracked in our issues repo at Azure/service-fabric-issues#563

**Comment by Eneuman** [comment]
@ravipal @amanbha I just tried the latest version and this problem still occurs.

**Comment by amanbha** [comment]
@Eneuman This issue of assembly resolve is being tracked as Stateful service issue at https://github.com/Azure/service-fabric-issues/issues/563 Could you please update that issue. Thanks

**Comment by Eneuman** [comment]
@amanbha I'm not sure if this is the exact problem, cause now I'm just receiving 
`The program '[7936] Web1.exe' has exited with code -2146232797 (0x80131623).`

I'll open a new issue for this since the not found file exception is gone.

**Comment by amanbha** [comment]
@Eneuman Sounds good, makes sense, Thanks. if its not specific to aspnet core, please open it in our general issues repo at https://github.com/Azure/service-fabric-issues/issues
