### ISSUE TITLE
Reverse Proxy + HttpContext.RequestAborted

### ISSUE THREAD

**Issue by MrMint** [Azure/service-fabric-aspnetcore#39]
We are looking to utilize the HttpContext.RequestAborted in order to cleanly cancel expensive requests that are no longer needed, however have ran into an issue when using the Reverse Proxy.

We are using the KestrelCommunicationListener, and have confirmed that connecting directly to the aspnetcore app and canceling the request triggers the cancellation token. When connecting via the reverse proxy, the cancellation token is never triggered. We moved over to kestrel as IIS was previously blocking the cancellation from working, is the reverse proxy in the same boat?

Is this expected behavior, if not are there any workarounds?

**Comment by amanbha** [comment]
@kavyako

**Comment by kavyako** [comment]
Unfortunately reverse proxy is HTTP.SYS based and will fall into the same boat. There is not cancellation support today. 
If the service is sending back chunked data to the client and the client disconnects the request to the reverse proxy, reverse proxy will close the request with the service and terminate the connection.

**Comment by MrMint** [comment]
Any idea if there are plans to move it over to kestrel? I noticed some of the other issues in this repo discussing ideas around a different reverse proxy [#12](https://github.com/Azure/service-fabric-aspnetcore/issues/12) , [#11](https://github.com/Azure/service-fabric-aspnetcore/issues/11).

This is a blocker for us and we will need to roll our own gateway in the meantime.

**Comment by amanbha** [comment]
@MrMint There are no plans to move it to Kestrel. You can leverage API Management with Service Fabric https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-api-management-overview

**Comment by MrMint** [comment]
Good to know, thanks!
