### ISSUE TITLE
Kestrel or HttpSys for stateless service exposed to reverse proxy

### ISSUE THREAD

**Issue by Tadimsky** [Azure/service-fabric-aspnetcore#41]
I'm having a hard time understanding the documentation that is out there in terms of whether to use HttpSys or Kestrel for our stateless services that are exposed to the Web via a reverse proxy.

I am running Azure Application Gateway, which then has the SF cluster set as the backend machine. We require end-to-end encryption on the traffic and so I need to have the SF application use HTTPS.

It seems like I can either use Kestrel and the `UseHttps` option or use `HttpSys`.
I've been reading a lot of stuff recommending to not use Kestrel when exposing it to the world (I guess unless it's behind a Reverse Proxy  - which it is), but [your docs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore#scenarios-and-configurations) seem to recommend Kestrel for this option.

What would you recommend at the moment for doing this? `HttpSys` _seems_ to be easier to configure HTTPS as it is built into Service Fabric a little better, whereas for `Kestrel` I'd need to do the retrieval of the certificate manually.

**Comment by amanbha** [comment]
If you are on windows and need port sharing use httpsys.
If you are on linux you will have to use Kestrel.
Reverse Proxy with Kestrel is needed in scenarios described here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x#when-to-use-kestrel-with-a-reverse-proxy

**Comment by Tadimsky** [comment]
We are running on Windows machines, but do not need port sharing (running each frontend service on its own port). We have rules on the Application Gateway to route to the right backend service.
So which one would you recommend knowing that?

**Comment by amanbha** [comment]
@Tadimsky Use Kestrel.

**Comment by Tadimsky** [comment]
Ok, thanks. Is the reason you recommend that because Kestrel is the recommended host for ASP.NET Core in general? 

So if I do that, then I don't set anything to do with SSL Cert in the [Endpoint config](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-service-manifest-resources) for the Service right? Like so:
```
<Resources>
  <Endpoints>
    <Endpoint Name="HttpsServiceEndpoint" Protocol="https" Port="9062" />
  </Endpoints>
</Resources>
```

I would need to ACL the cert so that the NETWORK SERVICE user can access it (same as the Config cert) and then use it directly in the `UseHttps` method?
Is it still worth defining the Endpoint in the Service Manifest at all? I assume it's the benefits listed here that matter:  [Kestrel in Reliable Services](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore#kestrel-in-reliable-services)

Do you know if there is a sample somewhere of a stateless ASP.NET Core app using Kestrel with HTTPS that I could take a look at?

**Comment by amanbha** [comment]
Yes, its recommended host. If you want port sharing then use httpsys. Yes you are right you will have to acl the private key of cert to the user service would run under(by default it would run under NETWORKSERVICE).
Yes, the benefits for specifying endpoint are listed in the link you shared.
I am not aware of a sample published, but following code snippet , should do https with kestrel aspnetcore 2.0:
`
  protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new ServiceInstanceListener[]
            {
                new ServiceInstanceListener(serviceContext =>
                    new KestrelCommunicationListener(serviceContext, (url, listener) =>
                    {
                        ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting Kestrel on {url}");

                        return new WebHostBuilder()
                                    .UseKestrel(options => {
                                    options.Listen(IPAddress.IPv6Any, 0, listenOption =>
                                    {
                                        listenOption.UseHttps(GetCertificate());
                                            });
                                    }
                            )
                                    .ConfigureServices(
                                        services => services
                                            .AddSingleton<StatelessServiceContext>(serviceContext))
                                    .UseContentRoot(Directory.GetCurrentDirectory())
                                    .UseStartup<Startup>()
                                    .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                                    .Build();
                    }))
            };
        }
`

**Comment by Tadimsky** [comment]
Ok, thank you!

So we no longer use the `url` parameter provided in the `UseUrls` function. 
For the `Listen` function, should this not be pulled from the Endpoint config for port? Or is it ok to use 0 as the port? And is `IPAddress.IPv6Any` the recommended one to use?

**Comment by amanbha** [comment]
yes, if you are using dynamic port, then use port 0 and you don't need any endpoint in service manifest.
If its listening on a static port specified in service manifest, you will have to read it from Endpoint config, 
it will be in the url also, you can extract from url string. 
Yes, IPV6Any is recommended way.

**Comment by Tadimsky** [comment]
Ok, great - I'll try that. Thank you 😄

**Comment by Tadimsky** [comment]
So it looks like I had to specify the certificate as a `SecretsCertificate` instead of an `EndpointCertificate` and then it works fine. Is this ok?

```xml
           </Section>
           <Section Name="Host">
             <Parameter Name="AllowHttp" Value="[WhiteboardsApi_AllowHttp]" />
+            <Parameter Name="SslThumbprint" Value="[SslCertificateThumbprint]" />
           </Section>
         </Settings>
       </ConfigOverride>
@@ -33,9 +34,6 @@
       <!-- Set the environment variable for ASP.Net Core so that it knows its environment like usual -->
       <EnvironmentVariable Name="ASPNETCORE_ENVIRONMENT" Value="[Environment]" />
     </EnvironmentOverrides>
-    <Policies>
-      <EndpointBindingPolicy EndpointRef="HttpsServiceEndpoint" CertificateRef="SslCert" />
-    </Policies>
   </ServiceManifestImport>
   <DefaultServices>
     <!-- The section below creates instances of service types, when an instance of this
@@ -57,10 +55,11 @@
   <Policies>
     <SecurityAccessPolicies>
       <SecurityAccessPolicy ResourceRef="SecretCert" PrincipalRef="ServiceUser" ResourceType="Certificate" />
+      <SecurityAccessPolicy ResourceRef="SslCert" PrincipalRef="ServiceUser" ResourceType="Certificate" />
     </SecurityAccessPolicies>
   </Policies>
   <Certificates>
     <SecretsCertificate X509FindValue="[ConfigCertificateThumbprint]" Name="SecretCert" />
-    <EndpointCertificate X509FindValue="[SslCertificateThumbprint]" Name="SslCert" />
+    <SecretsCertificate X509FindValue="[SslCertificateThumbprint]" Name="SslCert" />
   </Certificates>
 </ApplicationManifest>
```

**Comment by amanbha** [comment]
@Tadimsky The endpoint cert is httpsys, it has no impact for kestrel SecretCert works for this scenario as it ACLs the cert also but is not the intended use of SecretCert I know its little arcane to explain, we plan to simplify this cert story in future releases. Usually users setup the cert by running some script to acl cert private key to network service sid:
1.  [(setup entry point](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-runas-security#configure-the-policy-for-a-service-setup-entry-point)  of your code package (setup entry point can be run as Local system to do ACl.). 

2. If the cluster is on-premise, then the script can be run on all nodes. If the cluster is in Azure, it can be run by adding to ARM template.

**Comment by Tadimsky** [comment]
@amanbha just wanted to check if there was some content missing in your response - there is a bulleted list of just one item.

If `SecretsCertificate` is working for me, is that ok to use?

**Comment by amanbha** [comment]
@Tadimsky Thanks for pointing it out, indeed it was clipped somehow, I updated my my response above to include another point.
Reg. SecretCertificate, I know it works because of how its implemented and this is not its intended purpose, using it would still fall into a workaround category and dependent on implementation detail, it might change in future,

**Comment by Tadimsky** [comment]
Ok, great - thank you @amanbha - using `SecretsCertificate` definitely feels hacky and so not a huge fan of it. I'll look into how to ACL the cert using a script run at deployment via ARM.
Is there any info and ETA on the certificate improvements you mentioned? (Internal only? - my alias is `joschm`)

**Comment by amanbha** [comment]
@Tadimsky its in backlog as we have other high priority work items so don't have firm ETA at this moment.
I am closing this for now, if you have further questions, feel free to ping me or open other issue.
