### ISSUE TITLE
Potentially leaking WebHostBuilder in CreateServiceInstanceListeners()

### ISSUE THREAD

**Issue by billysug** [Azure/service-fabric-aspnetcore#45]
Can we look into this potential issue leaking WebHostBuilder in CreateServiceInstanceListeners().  Is this supposed to be cleaned up in StatelessService.OnCloseAsync() or ICommunicationListener.CloseAsync()?  Should the customer write any code to override StatelessService.OnCloseAsync() as stated in documentation?

0:000> !dumpheap -type WebHostBuilder -stat
Statistics:
              MT    Count    TotalSize Class Name
00007ffdcd25a1c8        1           24 Microsoft.AspNetCore.Hosting.ApplicationInsightsWebHostBuilderExtensions+<>c
00007ffdcd259f10        1           24 Microsoft.AspNetCore.Hosting.WebHostBuilderHttpSysExtensions+<>c
00007ffdcd2530f0        1           24 System.Action`2[[Microsoft.AspNetCore.Hosting.WebHostBuilderContext, Microsoft.AspNetCore.Hosting.Abstractions],[Microsoft.Extensions.Configuration.IConfigurationBuilder, Microsoft.Extensions.Configuration.Abstractions]][]
00007ffdcd252e60        1           24 System.Action`2[[Microsoft.AspNetCore.Hosting.WebHostBuilderContext, Microsoft.AspNetCore.Hosting.Abstractions],[Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.Extensions.DependencyInjection.Abstractions]][]
00007ffdcd25a0f0      126         4032 Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions+<>c__DisplayClass1_0
00007ffdcd250888      126         4032 Microsoft.AspNetCore.Hosting.WebHostBuilderContext

**Comment by amanbha** [comment]
WebHost is disposed in CloseAsync https://github.com/Azure/service-fabric-aspnetcore/blob/01bec82608e9ae280a4ac4ecd2ba28a5c2467744/src/Microsoft.ServiceFabric.AspNetCore/AspNetCoreCommunicationListener.cs#L125

WebHostBuilder is not given to CommunicationListener, it only gets WebHost from user code, so WebHostBuilder cant be disposed in CommunicationListener. 
Please clarify if I missed something here.

**Comment by amanbha** [comment]
@billysug I am closing it, please feel free to reopen if you need more help.
