### ISSUE TITLE
HttpSys single port sharing random 503 service unavailable

### ISSUE THREAD

**Issue by lilraft** [Azure/service-fabric-aspnetcore#49]
I'm hosting several .net core 2.0 stateless services under Azure service fabric with 3 nodes staging cluster and now trying to set up single port sharing between them via HttpSys & HttpSysCommunicationListener (as described here https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore#httpsys-in-reliable-services ).
Each service has 2 instances.

**CreateServiceInstanceListeners :** (second service CreateServiceInstanceListeners method is the same with just a different endpoint name & url prefix)
``` csharp
return new[]
{
                new ServiceInstanceListener(serviceContext =>
                    new HttpSysCommunicationListener(serviceContext, "WebAPICoreServiceEndpointHttps",
                        (url, listener) =>
                        {
                            return new WebHostBuilder().UseHttpSys().ConfigureServices(
								services => services.AddSingleton(serviceContext))
								.UseContentRoot(Directory.GetCurrentDirectory())
								.UseStartup<Startup>()
								.UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
								.UseUrls($"{url}/WebAPICore")
                                .ConfigureAppConfiguration((hostingContext, config) =>
                                {
                                    var configuration = ConfigureEnvironment(hostingContext, config);
                                    Log.Logger = new LoggerConfiguration()
                                        .ReadFrom
                                        .Configuration(configuration)
                                        .WriteTo.ApplicationInsightsTraces(
                                            configuration.GetSection("ApplicationInsights:InstrumentationKey").Value)
                                        .CreateLogger();
                                })
                                .ConfigureLogging((hostingContext, logging) =>
                                {
                                    logging.AddSerilog(dispose: true);
                                })
                                .UseApplicationInsights()
                                .Build();
                        }))
            };
```

Each service has it's unique url prefix and same port in ServiceManifest enpoint settings. 
**ServiceManifest 1 :**
``` xml
<Resources>
    <Endpoints>
      <Endpoint Protocol="https" Name="WebAPICoreServiceEndpointHttps" Type="Input" Port="8162" PathSuffix="/WebAPICore" />
    </Endpoints>
  </Resources>
````
**ServiceManifest 2 :**
``` xml
<Resources>
    <Endpoints>
      <Endpoint Protocol="https" Name="SecondAPIServiceEndpointHttps" Type="Input" Port="8162" PathSuffix="/SecondAPI" />
    </Endpoints>
  </Resources>
````

Despite all that I randomly receive "503 service unavailable" from the specified endpoints (aprox. 1 of 5 same requests ends up with 503). Load balancer rule and probe is also set up. This case only takes place in Azure service fabric. Local cluster works fine.

**Balancing Rule :**
It's an IPv4 TCP rule from port 443 to 8162 backend and 5 mins idle timeout

 **Health probe :**
It's an IPv4 TCP 8162 probe with 5 sec interval and 2 consecutive failures threshold

**Comment by amanbha** [comment]
@lilraft 
Lets consider the scenario which you have explained:
You have 2 instances of services S1 & S2 in a 3 node cluster N1, N2 and N3, lets says service instances are deployed in following way:
- N1 has S1, S2
- N2 has S1
- N3 has S2

Now your load balancer is configured to forward traffic to 8162 for both the services, Only following calls will be serviced:
- calls for S1 routed to N1 and N2 
- calls for S2 routed to N1 and N3.

If load balancer sends call to N2 for S2 and to N3 for S1, then it cannot be serviced.
Could you try with instance count of -1 for these services, that should work.

**Comment by lilraft** [comment]
@amanbha thanks! this helps!

**Comment by amanbha** [comment]
@lilraft I am closing this issue, please feel free to reopen if you have any more questions.
