### ISSUE TITLE
DependancyInjection

### ISSUE THREAD

**Issue by grahamehorner** [Azure/service-fabric-aspnetcore#5]
make it easier to allow switching between Docker & ServiceFabic deployments of AspNetCore stateless Web/Web API by using DependancyInjection to build the appropriate WebHost according to what environment/deployment

**Comment by vturecek** [comment]
@grahamehorner Do you have an example of what you have in mind?

**Comment by grahamehorner** [comment]
open to ideas; at present the entry point for a ASP.NET MVC or WebAPI is main; however this is not the case for ServiceFabric as the instantiation is somewhat different; I feel these should be unified so that the entry point/flow can be used with DependancyInjection handling the wrapping/or injection of additional features when running under ServiceFabric

**Comment by Mardoxx** [comment]
I don't follow. Can you provide an example, or counter example pointing out what is wrong?

**Comment by amanbha** [comment]
@grahamehorner Could you please explain this a bit more.

**Comment by amanbha** [comment]
didn't hear back from you. If this is still a concern then, then please reopen this issue along with more explanation as to what is missing and what is expected.
