### ISSUE TITLE
dotnet restore fails on sfproj when netcoreapp2.0 are referenced

### ISSUE THREAD

**Issue by vitalybibikov** [Azure/service-fabric-aspnetcore#50]
Currently in solution we have several netcoreapp2.0/net47 services that are referenced by sfproj.

When solution is built using MSBUILD/VS 2017 it builds just fine,
but when we are assembling the solution using "dotnet build" or restoring it with "dotnet restore"
it breaks with 

` ServiceFabricApplication.sfproj(61,5): error : Unable to find the '..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.4\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package.`

**Comment by dbreshears** [comment]
@EvilAvenger ,  dotnet build/restore is not something we currently support with .sfproj since our underlying project system is not dotnet core based.   You would indeed need to use MSBuild.

**Comment by vitalybibikov** [comment]
I know, still we have a lot of issues with MsBuild. The desire is to throw it away from our CI/CD.

https://github.com/Microsoft/service-fabric/issues/142 is an example.

**Comment by ryandle** [comment]
@dbreshears It's been 2.5 years - can this be reconsidered now? dotnet core tooling is a must-have for developers these days. It would be wonderful if building .sfproj supported it, because then our entire build pipeline could just use dotnet core tooling.

**Comment by cjfarrelly** [comment]
Same ask here, why are sfproj still not net core?

**Comment by AmirSasson** [comment]
hi @dbreshears, i was wondering if there is  anything new here?
is the alternative is to "give up" on the SFPROJ file and follow [this ](https://github.com/Azure-Samples/service-fabric-dotnet-core-getting-started) is the only alternative?
