### ISSUE TITLE
Better configuration source support for hierarchical settings for shared library in multiple environments

### ISSUE THREAD

**Issue by chuanboz** [Azure/service-fabric-aspnetcore#52]
# Background
For a large product in a large organization (like Microsoft Intune), we have Infra team that handle common horizontal logics apply to all the Microservice in the product, we also have Microservice team that actually own the service logic deployed to Service Fabric. Infra team and Microservice team have different repos and we also have different environments like development, staging, perf, production etc.

# Workflow and Issues
Let's take throttling as an example to illustrate the workflow here and the ask is to better support such workflow.

Infra team will provide a common Throttle library in Infra repo, that consist of Throttle.dll and default Throttle settings, the default settings might also have different override for the above supported environments, so here is the folder structure of the generated Throttle package:
-- lib
-----Throttle.dll
--Config
-----ThrottleSettings.Default.xml (or Json)
-----ThrottleSettings.Default.Perf.xml (or Json)

Let's say a Microservice team for UserApp and UserService that used the Infra throttle package to support request throttle, as UserService is a high volume service, the default settings from Infra does not work and so they need to override it, and also need to specify the different settings for perf and production environments, so Microservice team also needs ThrottleSettings.xml and ThrottleSettings.Perf.xml.

Here are the challenge and issues:
1. How to apply the settings in the desired order:
Let's say current environment is Perf, then it needs to be applied in following order:
a. ThrottleSettings.Default.xml
b. ThrottleSettings.Default.Perf.xml
c. ThrottleSettings.xml
d. ThrottleSettings.Perf.xml
Step b, c, d could be optional as such override might not exists for certain service or environments.

# Solution 1 with Service Fabric Settings.xml in Config Package.
Follow [How to parameterize configuration files in Service Fabric](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-how-to-parameterize-configuration-files)
As config package Settings.xml has only one xml file, there needs to be some build process to merge above settings to generate the environment specific ApplicationManifest.xml

**Pros**: built-in Config parameter override support.

**Cons**: 
1. Settings spread across ApplicationManifest.xml, Parameters.xml and ServiceManifest.xml
2. Need custom home-grown packaging tool to modify the XML files.

# Solution 2 with Service Fabric Config/Data Package and use Json files.
Follow the standard asp.net core [Work with multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1), specifically just load the following Json files in ConfigureAppConfiguration and then asp.net core will handle the parameter override.

- throttleSettings.Default.json
- throttleSettings.Default..< Environment >.json
- throttleSettings.json
- throttleSettings.< Environment >.json

For deployment process, simply merge all the ThrottleSettings.*.Json as is to the final deployable package in Data or Config folder, and then leverage asp.net configuration override to load all the Json files based on their sequence of applying order.

**Pros**: 
1. More flexible settings format in Json file, does not need to be limit by the Settings.xml schema, could naturally have multiple level of hierarchy than just Section/Parameter.
2. Naturally work with above workflow, no need for custom merge tool.

**Cons**: 
1. Need custom way to load the Json file and hook up with Service Fabric change notification to reload the json file.

# Ask
the ask is to add better support for above workflow and provide standard Service Fabric config source to hook up with Service Fabric change notification to reload the json file.

I could contribute to this if you agree on the approach in above solution 2, it will need to take dependency on NewtonSoft.Json package.

**Comment by amanbha** [comment]
Approach 1 is same as https://github.com/Azure/service-fabric-aspnetcore/issues/9 for configuration package
@chuanboz  For approach 1, the settings don't need to be spread across manifests, you only need to do that if you are overriding the values using application a parameters. Could you explain more about the cons? Overriding the settings values using application manifest is a huge pros.

Adding @vturecek also for approach 2 above.

**Comment by chuanboz** [comment]
#9 does not have the multiple team/repo support, it work for the case where one team fully own the settings authoring experience. As I call out, in our workflow we have at least 2 teams own the experiences, infra team own the default settings in one repo, and Microservice team own more specific override, and those settings eventually needs to be merge. We do not want such merge process to be manual.

**Comment by amanbha** [comment]
@chuanboz For the scenario you mentioned, you don't need to merge application manifest to support parameter overrides. The parameter overrides happen at application creation time https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-manage-multiple-environment-app-configuration#specifying-parameters-during-application-creation

**Comment by chuanboz** [comment]
I checked the link you give, that still does not work well for our workflow. because for parameter override to work, the application manifest needs to define those parameters first.
the conflict that I see is, in our case Infra team define the default settings and every parameters could be override-able, we do not require Microservice team to declare it to override the value, they just make a copy and change the value directly for the entry they want to override, that's much simpler and intuitive experience than is called out in the link you give.

One of the key difference that I see, the Settings.xml parameter override experience, you have to declare what you want to override in one place, and then override it in another place.

As a comparison, the Json file override experience I called out in solution 2, the user just modify one Json file and override it in the same place directly.

And throttle settings is just one example, we have many different of settings parameter (more than 100) and every parameter in those settings we support to override, require user to declare all of the parameters that they override is lots of work; and we also have more than 100 services; those 2 factors combined together that really show the difference in solution 1 and solution 2, that solution 2 is much more agile for us to enable.

**Comment by amanbha** [comment]
@chuanboz  So basically you are just overriding the config value directly in the built package (settings or json) rather than overriding it when creating application. Scenario which you are explaining is too specific to your use case. and doesn't apply to every in general. Sorry but solution 2 isn't very generic and too specific for the use case. 
Most users override the values using application parameters. Lets implement the solution 1.

**Comment by chuanboz** [comment]
I just find a good balance that does not require SF aspnetcore package to dependent on Newtonsoft.Json, while still enable my scenario, by expose a config action delegate so that I could implement that delegate myself in my repo, will that be OK for you?

```C#
        /// <summary>
        /// Add configuration for all the configuration packages declared for current service.
        /// </summary>
        public static IConfigurationBuilder AddServiceFabricConfiguration(this IConfigurationBuilder builder)
        {
            var context = FabricRuntime.GetActivationContext();
            foreach (var packageName in context.GetConfigurationPackageNames())
            {
                builder.Add(new ServiceFabricConfigurationSource(packageName));
            }

            return builder;
        }

        /// <summary>
        /// Add configuration for given configuration package from packageName parameter
        /// </summary>
        public static IConfigurationBuilder AddServiceFabricConfiguration(this IConfigurationBuilder builder, string packageName)
        {
            return builder.Add(new ServiceFabricConfigurationSource(packageName));
        }

        /// <summary>
        /// Add configuration for given configuration package from packageName parameter as well as customize config action to populate the Data.
        /// </summary>
        public static IConfigurationBuilder AddServiceFabricConfiguration(
            this IConfigurationBuilder builder, string packageName, 
            Action<ConfigurationPackage, IDictionary<string, string>> configAction = default)
        {
            return builder.Add(new ServiceFabricConfigurationSource(packageName, configAction));
        }
```

so the advanced end user will provide the configAction to enable their specific use case in solution 2, but majority people could still use the default experience for solution 1.

**Comment by amanbha** [comment]
Thanks @chuanboz  Introducing that extension point seems doable. We can discuss about it, we're busy right now with the Build conference coming up, but in a couple weeks we'll definitely take a close look at this. In the meantime you can prepare the PR for Solution 1.

**Comment by amanbha** [comment]
@chuanboz Tracking this with #9 , As discussed during our skype call, please share the PR for it when available. Thanks!
