### ISSUE TITLE
Update asp.net core dependency to 2.0

### ISSUE THREAD

**Issue by chuanboz** [Azure/service-fabric-aspnetcore#53]
I just find the current asp.net core dependency used is 1.0, which is very old.

Suggest to update it to 2.0, and might consider to bump it to 2.1 a few months later when asp.net core 2.1 released.

**Comment by amanbha** [comment]
@chuanboz thanks for the suggestion, but we can't update that because our users are still using aspnetcore 1.0 and 1.1.
You can update the aspnetcore package in your service.
