### ISSUE TITLE
Test support: expose public constructor for sealed class used in ICodePackageActivationContext interface

### ISSUE THREAD

**Issue by chuanboz** [Azure/service-fabric-aspnetcore#54]
While implementing #48 and #9 , I'm trying to provide a complete test that could fully cover the logic, I found that ICodePackageActivationContext interface has referenced many sealed class in System.Fabric that does not have public constructor.

Some examples are:
1. ConfigurationPackage
2. ConfigurationPackageDescription
3. ConfigurationSettings
4. ConfigurationSection

Right now one workaround that I see is to use Microsoft Fakes, that could work for .net framework but does not work for .net core. 

It would be best if such class could provide a public constructor even making it sealed, so that in my test I could create instances of ICodePackageActivationContext and test the behavior.

**Comment by amanbha** [comment]
Thanks @chuanboz for bringing this up, I understand the issue which sealed classes with no public constructor poses when it comes to mocking. This repo tracks issues related to aspnet core service fabric integration, the issue you mentioned is for Service Fabric in general, could you please open this under Service Fabric issues repo at https://github.com/Azure/service-fabric-issues/issues

**Comment by amanbha** [comment]
Closing it as its being tracked in Service Fabric Issues repo at https://github.com/Azure/service-fabric-issues/issues/1048
