### ISSUE TITLE
SpaServices / Webpack with Service Fabric

### ISSUE THREAD

**Issue by CuddleBunny** [Azure/service-fabric-aspnetcore#59]
Not really sure where the best place to put this is, but I've been trying to create a front-end web service with webpack / HMR @ dev time. After struggling for a while trying to implement on my own I added a copy of the Angular SpaServices project only to find that even that one does not support HMR and just builds one time on publish.

It kinda makes sense that this wouldn't work (except perhaps with Refresh Mode?), but it is misleading that it is included in the template. I've yet to figure out a way to support this workflow aside from having the web client run outside of service fabric during dev time.

**Comment by amanbha** [comment]
@CuddleBunny https://github.com/Azure/service-fabric-issues/issues would be a better place for this

**Comment by CuddleBunny** [comment]
@amanbha - thanks. Seems like it does work with refresh mode, I'll close this issue. 

Edit: Spoke too soon, will open a new issue there.
