### ISSUE TITLE
Move Configuration extensions to Microsoft.Extensions.DependencyInjection 

### ISSUE THREAD

**Issue by RamjotSingh** [Azure/service-fabric-aspnetcore#64]
The extension method for add configuration provider is in Microsoft.ServiceFabric namespace. Usually packages (like AppInsights and others) tend to add these methods to Microsoft.Extensions.DependencyInjection namespace. Do you think it will be better to move it there for easy discoverability?

@amanbha @chuanboz

**Comment by chuanboz** [comment]
I do notice this myself, but couldn't find an official recommendation on that for namespace. Do you know if there is any public document specifically called that out as recommendation?

**Comment by RamjotSingh** [comment]
I can't really find documentation on it. However AzureKeyVault, File and JsonFile all providers have their extensions in Microsoft.Extensions.Configuration namespace. Maybe it makes sense for SF to move it there as well?

**Comment by amanbha** [comment]
If there is no official doc or suggestion, then let's keep it in SF namespace and follow the convention of this repo.
