### ISSUE TITLE
Microsoft.ServiceFabric.AspNetCore.Configuration package missing on nuget.org

### ISSUE THREAD

**Issue by RicoSuter** [Azure/service-fabric-aspnetcore#69]
**Describe the bug**
According to the description, there should be a NuGet package with the ID "Microsoft.ServiceFabric.AspNetCore.Configuration" but we cannot find it on nuget.org

**To Reproduce**
Go to https://www.nuget.org/packages/Microsoft.ServiceFabric.AspNetCore.Configuration/ => 404

**Expected behavior**
There should be a package on nuget.org

**Additional context**
Is there a reason why this has not been published?

**Comment by shessane** [comment]
The package Microsoft.ServiceFabric.AspNetCore.Configuration is not yet released. You are reading the description of the develop branch.

You can look at some release branch description, there is no mention of this package.

However I'm curious to know when the team will release (or pre-release) this package

**Comment by RicoSuter** [comment]
@shessane thanks for your answer.
@amanbha do you have an ETA?

**Comment by amanbha** [comment]
@chuanboz Have you tested the package in your environment, and documented the usage, please let me know and we can discuss the release dynamics of this package.

**Comment by chuanboz** [comment]
The package is working well in my test environment but we haven't used it in production environment yet. For documented, it's tracked in https://github.com/MicrosoftDocs/azure-docs/issues/17193, I haven't do it yet but let me start to add it.

**Comment by chuanboz** [comment]
@amanbha, I've added document and sent a document PR here: https://github.com/MicrosoftDocs/azure-docs/pull/25809.

@RSuter  and @shessane, please also help me review the document PR to make sure usage is clear and easy to follow for you.

**Comment by chuanboz** [comment]
@amanbha , PR is merged in Azure Docs private repo https://github.com/MicrosoftDocs/azure-docs-pr/pull/68034

**Comment by amanbha** [comment]
Thanks @chuanboz I will look into releasing the nuget for it soon.

**Comment by amanbha** [comment]
Itss released on nuget.org https://www.nuget.org/packages/Microsoft.ServiceFabric.AspNetCore.Configuration/
