### ISSUE TITLE
Getting 502 BadGateway Error

### ISSUE THREAD

**Issue by mathavanmani** [Azure/service-fabric-aspnetcore#72]
Hi,

Getting 502, BadGateway error part of the Service Fabric ASP.Net core web API.

One  of the Put Method I have got part of a controller takes more than 10 mins to execute, But I'm getting 502/BadGateway response in 2 mins time. I have done the following bits.

1. Setting timeout part of KestrelCommunicationListener
    return new WebHostBuilder()
                                    .UseKestrel(o => {o.Limits.KeepAliveTimeout = TimeSpan.FromHours(1);})
                                    .ConfigureServices(
                                        services => services
                                            .AddSingleton<StatelessServiceContext>(serviceContext))
                                    .UseContentRoot(Directory.GetCurrentDirectory())
                                    .UseStartup<Startup>()                                    
                                    .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                                    .UseUrls(url)
                                    .Build();

2. Also set the time out in web.config.

3. Have also set the client timeout part of HttpClient initialization.

Please let me know how I can resolve this issue.

**Comment by amanbha** [comment]
@mathavanmani  This doesn't seems like a Service Fabric issue, could you debug your service code for this call?
