### ISSUE TITLE
Fix misleading packagename

### ISSUE THREAD

**Issue by 4nandP** [Azure/service-fabric-aspnetcore#89]
The package name _Microsoft.ServiceFabric.AspNetCore.Configuration_ is completely misleading and inconsistent. It should be 
_Microsoft.Extensions.Configuration.ServiceFabric_, which will make it easier to find and increase adoption

**Comment by amanbha** [comment]
@4nandP Changing it now would be a breaking change, As per guidance the package name would start with Microsoft.ServiceFabric and the team has only reserved to publish packages with Microsoft.ServiceFabric prefix.
Any other suggestions to make it more discoverable in documentation is welcome.
